version: '3.8'

services:
  app:
    image: php:8.2-fpm
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - laravel
    ports:
      - "5035:8090"

  webserver:
    image: nginx:latest
    container_name: laravel_webserver
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kenodb
      MYSQL_USER: root
      MYSQL_PASSWORD:
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:

volumes:
  mysql_data:
